name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  DependenciesAnalysis:
    name: Analyse Semgrep (Java)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep --config=p/java --sarif --output=semgrep-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif

  SourceCodeAnalysis:
    name: Analyse OSV Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OSV Scanner
        run: |
          curl -sSfL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run OSV Scanner
        run: osv-scanner --lockfile=**/package-lock.json --output osv-report.sarif || true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-report.sarif
